name: Docker Pipeline
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3        
        with:
          username: ${{ secrets.DOCKER_HUB_LUNASCORE }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        run: docker build -t kibromberihu/lunascore:latest .
      - name: push docker image
        run: docker push kibromberihu/lunascore:latest
        
    
